### PR TITLE
Add class version for easy implementation

### PR DESCRIPTION
**Pull request by gpronost**

### CODE REVIEW

**Comment by tdealtry** [comment]
Thank you for doing this @gpronost This is really helpful for the DAQ group

I've just tried to compile the leaf directory, and it's failing at this point (It also doesn't compile when I comment this line out)
```include ../Makefile/Makefile.${OSNAME}```

`$LEAFDIR/Makefile` doesn't exist, so it looks like you missed committing & pushing that directory. Could you please take a look? Thanks!

**Comment by gpronost** [comment]
Thank you for the check, I just add it

**Comment by gpronost** [comment]
I added the new directionnality function for mPMT
Time per event with mPMT is now ~0.2 sec. It could be improve by going to ROOT6.06 or newer, as the interpolation function is not compatible with multi-threading before this version.

**Comment by gpronost** [comment]
To celebrate the 100 commits ahead, let's merge (following discussion at software meeting)

**Pull request merged**
